# See https://github.com/marketplace/actions/changed-files
name: tsc

on:
  pull_request:
    branches:
      - main

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18.18.0

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Get all changed js and ts files
        id: changed-js-ts-files
        uses: tj-actions/changed-files@v44

        with:
          files_yaml: |
            js:
             **.js
            ts:
             **.ts
             **.tsx

      - name: For all changed js files
        if: steps.changed-js-ts-files.outputs.js_any_changed == 'true'
        env:
          JS_ALL_CHANGED_FILES: ${{ steps.changed-js-ts-files.outputs.js_all_changed_files }}
        run: |
          for file in ${JS_ALL_CHANGED_FILES}; do
            echo "$file was changed"
            npx eslint $file
          done

      - name: For all changed ts files
        if: steps.changed-js-ts-files.outputs.ts_any_changed == 'true'
        env:
          TS_ALL_CHANGED_FILES: ${{ steps.changed-js-ts-files.outputs.ts_all_changed_files }}
        run: |
          for file in ${TS_ALL_CHANGED_FILES}; do
            echo "$file was changed"
            npx tsc --noEmit $file
            npx eslint $file
          done
